//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenOvf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenOvf.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xen Appliance Wizard.
        /// </summary>
        public static string CONVERT_APP_NAME {
            get {
                return ResourceManager.GetString("CONVERT_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted from VMware VMX.
        /// </summary>
        public static string CONVERT_VMX_VSSD_CAPTION {
            get {
                return ResourceManager.GetString("CONVERT_VMX_VSSD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted from Virtual PC.
        /// </summary>
        public static string CONVERT_VPC_VSSD_CAPTION {
            get {
                return ResourceManager.GetString("CONVERT_VPC_VSSD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted from XVA version 0.1.
        /// </summary>
        public static string CONVERT_XVA_VSSD_CAPTION {
            get {
                return ResourceManager.GetString("CONVERT_XVA_VSSD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string CULTURE_AVAILABLE {
            get {
                return ResourceManager.GetString("CULTURE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Run Once Disk to configure Linux for startup..
        /// </summary>
        public static string INSTALL_SECTION_INFO_1 {
            get {
                return ResourceManager.GetString("INSTALL_SECTION_INFO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM,FLOPPY,ISO,DISPLAY.
        /// </summary>
        public static string IS_DISK_RASD_FILTER {
            get {
                return ResourceManager.GetString("IS_DISK_RASD_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Specific Information.
        /// </summary>
        public static string OTHER_SYSTEM_SETTING_DESCRIPTION_1 {
            get {
                return ResourceManager.GetString("OTHER_SYSTEM_SETTING_DESCRIPTION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot Order: CD/DVD - Network - Disk.
        /// </summary>
        public static string OTHER_SYSTEM_SETTING_DESCRIPTION_2 {
            get {
                return ResourceManager.GetString("OTHER_SYSTEM_SETTING_DESCRIPTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Platform Information.
        /// </summary>
        public static string OTHER_SYSTEM_SETTING_DESCRIPTION_3 {
            get {
                return ResourceManager.GetString("OTHER_SYSTEM_SETTING_DESCRIPTION_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual GPU Information.
        /// </summary>
        public static string OTHER_SYSTEM_SETTING_DESCRIPTION_4 {
            get {
                return ResourceManager.GetString("OTHER_SYSTEM_SETTING_DESCRIPTION_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVS Accelerator Information.
        /// </summary>
        public static string OTHER_SYSTEM_SETTING_DESCRIPTION_5 {
            get {
                return ResourceManager.GetString("OTHER_SYSTEM_SETTING_DESCRIPTION_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVM Boot Parameters.
        /// </summary>
        public static string OTHER_SYSTEM_SETTING_DESCRIPTION_6 {
            get {
                return ResourceManager.GetString("OTHER_SYSTEM_SETTING_DESCRIPTION_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Volatile Random-Access Memory.
        /// </summary>
        public static string OTHER_SYSTEM_SETTING_DESCRIPTION_7 {
            get {
                return ResourceManager.GetString("OTHER_SYSTEM_SETTING_DESCRIPTION_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        public static string RASD_10_ALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("RASD_10_ALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Adapter.
        /// </summary>
        public static string RASD_10_CAPTION {
            get {
                return ResourceManager.GetString("RASD_10_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Adapter.
        /// </summary>
        public static string RASD_10_DESCRIPTION {
            get {
                return ResourceManager.GetString("RASD_10_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet Port.
        /// </summary>
        public static string RASD_10_ELEMENTNAME {
            get {
                return ResourceManager.GetString("RASD_10_ELEMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD Drives.
        /// </summary>
        public static string RASD_16_ALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("RASD_16_ALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD/DVD Drive.
        /// </summary>
        public static string RASD_16_CAPTION {
            get {
                return ResourceManager.GetString("RASD_16_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xen CD/DVD Drive Setting Data..
        /// </summary>
        public static string RASD_16_DESCRIPTION {
            get {
                return ResourceManager.GetString("RASD_16_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD/DVD Drive.
        /// </summary>
        public static string RASD_16_ELEMENTNAME {
            get {
                return ResourceManager.GetString("RASD_16_ELEMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        public static string RASD_19_ALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("RASD_19_ALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk Image.
        /// </summary>
        public static string RASD_19_CAPTION {
            get {
                return ResourceManager.GetString("RASD_19_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk Image.
        /// </summary>
        public static string RASD_19_DESCRIPTION {
            get {
                return ResourceManager.GetString("RASD_19_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk Image.
        /// </summary>
        public static string RASD_19_ELEMENTNAME {
            get {
                return ResourceManager.GetString("RASD_19_ELEMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Hard Disk Image.
        /// </summary>
        public static string RASD_19_RESOURCESUBTYPE {
            get {
                return ResourceManager.GetString("RASD_19_RESOURCESUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Cores.
        /// </summary>
        public static string RASD_3_ALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("RASD_3_ALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string RASD_3_CAPTION {
            get {
                return ResourceManager.GetString("RASD_3_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string RASD_3_DESCRIPTION {
            get {
                return ResourceManager.GetString("RASD_3_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string RASD_3_ELEMENTNAME {
            get {
                return ResourceManager.GetString("RASD_3_ELEMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte * 2^20.
        /// </summary>
        public static string RASD_4_ALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("RASD_4_ALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string RASD_4_CAPTION {
            get {
                return ResourceManager.GetString("RASD_4_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Setting Data.
        /// </summary>
        public static string RASD_4_DESCRIPTION {
            get {
                return ResourceManager.GetString("RASD_4_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string RASD_4_ELEMENTNAME {
            get {
                return ResourceManager.GetString("RASD_4_ELEMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Memory.
        /// </summary>
        public static string RASD_4_RESOURCESUBTYPE {
            get {
                return ResourceManager.GetString("RASD_4_RESOURCESUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string RASD_CONTROLLER_ALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_ALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Controller.
        /// </summary>
        public static string RASD_CONTROLLER_DESCRIPTION {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1} Controller.
        /// </summary>
        public static string RASD_CONTROLLER_ELEMENTNAME {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_ELEMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDE.
        /// </summary>
        public static string RASD_CONTROLLER_IDE {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_IDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER.
        /// </summary>
        public static string RASD_CONTROLLER_OTHER {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI.
        /// </summary>
        public static string RASD_CONTROLLER_SCSI {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_SCSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI BUS[{0}] LUN[{1}] PORT[{2}] TARGETID[{3}].
        /// </summary>
        public static string RASD_CONTROLLER_SCSI_DESCRIPTION {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_SCSI_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lsilogic.
        /// </summary>
        public static string RASD_CONTROLLER_SCSI_SUBTYPE {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_SCSI_SUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string RASD_CONTROLLER_UNKNOWN {
            get {
                return ResourceManager.GetString("RASD_CONTROLLER_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Element Name.
        /// </summary>
        public static string RASD_UNKNOWN_ELEMENTNAME {
            get {
                return ResourceManager.GetString("RASD_UNKNOWN_ELEMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Disks.
        /// </summary>
        public static string SECTION_DISK_INFO {
            get {
                return ResourceManager.GetString("SECTION_DISK_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        public static string SECTION_EULA_INFO {
            get {
                return ResourceManager.GetString("SECTION_EULA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Networks.
        /// </summary>
        public static string SECTION_NETWORK_INFO {
            get {
                return ResourceManager.GetString("SECTION_NETWORK_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XenOVF Created Export.
        /// </summary>
        public static string SECTION_OPERATINGSYSTEM_DESCRIPTION {
            get {
                return ResourceManager.GetString("SECTION_OPERATINGSYSTEM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Operating System.
        /// </summary>
        public static string SECTION_OPERATINGSYSTEM_INFO {
            get {
                return ResourceManager.GetString("SECTION_OPERATINGSYSTEM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.{1}.
        /// </summary>
        public static string SECTION_OPERATINGSYSTEM_VERSION {
            get {
                return ResourceManager.GetString("SECTION_OPERATINGSYSTEM_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Options.
        /// </summary>
        public static string SECTION_STARTUP_INFO {
            get {
                return ResourceManager.GetString("SECTION_STARTUP_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string VIRTUAL_DISK_DESC_CAPACITYALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("VIRTUAL_DISK_DESC_CAPACITYALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Hardware Requirements: {0} MB RAM; {1} CPU(s), {2} Disk(s), {3} Network(s).
        /// </summary>
        public static string VIRTUAL_HARDWARE_SECTION_INFO {
            get {
                return ResourceManager.GetString("VIRTUAL_HARDWARE_SECTION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVF/OVA Packages.
        /// </summary>
        public static string VIRTUAL_SYSTEM_COLLECTION_TYPE_INFO {
            get {
                return ResourceManager.GetString("VIRTUAL_SYSTEM_COLLECTION_TYPE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XenOVF Generated.
        /// </summary>
        public static string VIRTUAL_SYSTEM_TYPE_INFO {
            get {
                return ResourceManager.GetString("VIRTUAL_SYSTEM_TYPE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xen Virtual Machine.
        /// </summary>
        public static string VSSD_CAPTION {
            get {
                return ResourceManager.GetString("VSSD_CAPTION", resourceCulture);
            }
        }
    }
}
