name: Test Builds

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore Packages
        run: msbuild XenAdmin.sln -t:restore
      - name: Build Release solution
        run: msbuild XenAdmin.sln -property:Configuration=Release
      - name: Build Debug solution
        run: msbuild XenAdmin.sln -property:Configuration=Debug
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop-release
          path: XenAdmin/bin/Release/net481
      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop-debug
          path: XenAdmin/bin/Debug/net481
